### ISSUE TITLE
滑动不流畅

### ISSUE THREAD

**Issue by geqiancrazy** [jianghejie/XRecyclerView#12]
有头部的时候，当头部有一半出现在屏幕上时，向下滑动不了

**Comment by zhoujianhanyu** [comment]
private boolean isOnTop() {
if (mHeaderViews == null || mHeaderViews.isEmpty()) {
return false;
}

    View view = mHeaderViews.get(0);
    if (view.getParent() != null) {
        return true;
    } else {
        return false;
    }
// LayoutManager layoutManager = getLayoutManager();
// int firstVisibleItemPosition;
// if (layoutManager instanceof GridLayoutManager) {
// firstVisibleItemPosition = ((GridLayoutManager) layoutManager).findFirstVisibleItemPosition();
// } else if (layoutManager instanceof StaggeredGridLayoutManager) {
// int[] into = new int[((StaggeredGridLayoutManager) layoutManager).getSpanCount()];
// ((StaggeredGridLayoutManager) layoutManager).findFirstVisibleItemPositions(into);
// firstVisibleItemPosition = findMin(into);
// } else {
// firstVisibleItemPosition = ((LinearLayoutManager) layoutManager).findFirstVisibleItemPosition();
// }
// if (firstVisibleItemPosition < 1) {
// return true;
// }
// return false;
}

**Comment by jianghejie** [comment]
貌似可行，试试，感谢
