### ISSUE TITLE
关于 setEmptyView 

### ISSUE THREAD

**Issue by Knight-xiaolu** [jianghejie/XRecyclerView#123]
if (pullRefreshEnabled) {
                    emptyCount++;
                }
                if (loadingMoreEnabled) {
                    emptyCount++;
                }
建议将 pullRefreshEnable 跟loadingMoreEnable 的判断去掉 因为即使loadingMoreEnable=false,仍然会加入到recycleView 列表里面，当adapter里面没有数据的时候 adapter.getItemCount==2,但是emptyCount最小确实0，请看下你setEmptyView 的机制，这个有问题

**Comment by Knight-xiaolu** [comment]
刚我下了一个最新的版，看了下你这边已经改了。。可能我以前下的版本不是最新的

**Comment by zhuangchuming** [comment]
这个问题貌似是存在的，
if (pullRefreshEnabled) {
emptyCount++;
}
if (loadingMoreEnabled) {
emptyCount++;
}
这个要怎么跟adapter配合起来使用
