### ISSUE TITLE
AVLoadingIndicatorView内存泄漏了

### ISSUE THREAD

**Issue by findvoid** [jianghejie/XRecyclerView#161]

**Comment by af913337456** [comment]
## 参照我这篇博文解决，曾经就是这个 类，http://www.cnblogs.com/linguanh/p/5601232.html

**Comment by findvoid** [comment]
我已经修复了,谢谢

**Comment by af913337456** [comment]
good

**Comment by jianghejie** [comment]
hi，你俩来我的qq群讨论下呗 478803619

**Comment by xiayu98020214** [comment]
最新的1.3.2版本的还是内存泄漏

**Comment by af913337456** [comment]
楼上，自己单独采用我的方法修复

**Comment by findvoid** [comment]
修改这个文件即可

**Comment by xiayu98020214** [comment]
@findvoid @af913337456 我感觉root cause是这样子的啊。scaleAnim.start();alphaAnim.start(); 删掉这两句话。不觉得很奇怪吗？还没下来刷新，就start了。
com/jcodecraeer/xrecyclerview/progressindicator/indicator/BallSpinFadeLoaderIndicator.java
    @Override
    public List<Animator> createAnimation() {
        List<Animator> animators=new ArrayList<>();
        int[] delays= {0, 120, 240, 360, 480, 600, 720, 780, 840};
        for (int i = 0; i < 8; i++) {
            final int index=i;
            ValueAnimator scaleAnim=ValueAnimator.ofFloat(1,0.4f,1);
            scaleAnim.setDuration(1000);
            scaleAnim.setRepeatCount(-1);
            scaleAnim.setStartDelay(delays[i]);
            scaleAnim.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                @Override
                public void onAnimationUpdate(ValueAnimator animation) {
                    scaleFloats[index] = (float) animation.getAnimatedValue();
                    postInvalidate();
                }
            });
            scaleAnim.start(); //不觉得很奇怪吗？还没下来刷新，就start了

            ValueAnimator alphaAnim=ValueAnimator.ofInt(255, 77, 255);
            alphaAnim.setDuration(1000);
            alphaAnim.setRepeatCount(-1);
            alphaAnim.setStartDelay(delays[i]);
            alphaAnim.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                @Override
                public void onAnimationUpdate(ValueAnimator animation) {
                    alphas[index] = (int) animation.getAnimatedValue();
                    postInvalidate();
                }
            });
           alphaAnim.start(); //不觉得很奇怪吗？还没下来刷新，就start了**
            animators.add(scaleAnim);
            animators.add(alphaAnim);
        }
        return animators;
    }

**Comment by af913337456** [comment]
![image](https://cloud.githubusercontent.com/assets/10436277/21174444/1e5c311e-c218-11e6-9507-ecf4a4c61db8.png)

**Comment by xiayu98020214** [comment]
@af913337456  我用自己的方法也解决了。我认为动画没有end，是root cause。

**Comment by TOPWARNING** [comment]
AVLoadingIndicatorView在onlayout方法中开启了一个无限循环的Animation，在activity关闭的时候动画还在执行阶段，导致泄露
![image](https://cloud.githubusercontent.com/assets/6268829/23536760/12644aea-0002-11e7-8644-a1edbb3ddf8f.png)
![image](https://cloud.githubusercontent.com/assets/6268829/23536766/211c93f8-0002-11e7-9a05-92a6f934b33b.png)

**Comment by jan27th** [comment]
@af913337456 onDestroy方法在哪调用

**Comment by jan27th** [comment]
@findvoid 你好 可以贴一下完整代码么 小白一枚 十分感谢 学习下

**Comment by findvoid** [comment]
package com.jcodecraeer.xrecyclerview.progressindicator.indicator;

import android.animation.Animator;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.view.View;

import java.lang.ref.WeakReference;
import java.util.List;

/**
 * Created by Jack on 2015/10/15.
 */
public abstract class BaseIndicatorController {


    private WeakReference<View> mTarget;

    private List<Animator> mAnimators;


    public WeakReference<View> getTarget() {
        return mTarget;
    }

    public void setTarget(WeakReference<View> target) {
        this.mTarget = target;
    }

    public int getWidth() {
        if (mTarget.get() == null) {
            return 0;
        }
        return mTarget.get().getWidth();
    }

    public int getHeight() {
        if (mTarget.get() == null) {
            return 0;
        }
        return mTarget.get().getHeight();
    }

    public void postInvalidate() {
        if (mTarget.get() != null) {
            mTarget.get().postInvalidate();
        }
    }

    /**
     * draw indicator
     *
     * @param canvas
     * @param paint
     */
    public abstract void draw(Canvas canvas, Paint paint);

    /**
     * create animation or animations
     */
    public abstract List<Animator> createAnimation();

    public void initAnimation() {
        mAnimators = createAnimation();
    }

    /**
     * make animation to start or end when target
     * view was be Visible or Gone or Invisible.
     * make animation to cancel when target view
     * be onDetachedFromWindow.
     *
     * @param animStatus
     */
    public void setAnimationStatus(AnimStatus animStatus) {
        if (mAnimators == null) {
            return;
        }
        int count = mAnimators.size();
        for (int i = 0; i < count; i++) {
            Animator animator = mAnimators.get(i);
            boolean isRunning = animator.isRunning();
            switch (animStatus) {
                case START:
                    if (!isRunning) {
                        animator.start();
                    }
                    break;
                case END:
                    if (isRunning) {
                        animator.end();
                    }
                    break;
                case CANCEL:
                    if (isRunning) {
                        animator.cancel();
                    }
                    break;
            }
        }
    }


    public enum AnimStatus {
        START, END, CANCEL
    }


}

**Comment by jan27th** [comment]
@findvoid 好 答谢 WeakReference mTarget;这个变量是 WeakReference<View> mTarget吧; mIndicatorController.setTarget()里传什么啊，new一个 WeakReference<AVLoadingIndicatorView>么 不行啊 ，感谢赐教下 麻烦了

**Comment by jan27th** [comment]
@findvoid 写出来的 WeakReference<View> mTarget，发出来不显示了，求解 AVLoadingIndicatorView.setTarget(）里传什么啊？ 感谢求解下

**Comment by findvoid** [comment]
???? @jan27th

**Comment by findvoid** [comment]
mIndicatorController.setTarget(new WeakReference<View>(this));

**Comment by findvoid** [comment]
AVLoadingIndicatorView.java  applyIndicator()最后一行

**Comment by jan27th** [comment]
@findvoid  好 多谢 之前我也加了 但是报错 是因为我没有对mTarget.get() 判空
