### ISSUE TITLE
添加的header在Fragment中的布局属性没有效果？

### ISSUE THREAD

**Issue by WaylanPunch** [jianghejie/XRecyclerView#17]
header中的

> android:layout_width="match_parent"
> android:layout_height="200dip"

没有产生效果

![](http://i12.tietuku.com/a00d836d7a640627.png)

**Comment by jianghejie** [comment]
这个不是bug，请注意LayoutInflater.from(context).inflate(
				R.layout.xxx, null);和 LayoutInflater.from(context).inflate(R.layout.xxx, root,false);两种使用方式的区别。

**Comment by sungerk** [comment]
区别http://www.cnblogs.com/HighFun/p/3281674.html

我也遇到了这个问题。你可以这样试试。我解决了。

 private View header;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        header = inflater.inflate(R.layout.recyclerview_header, container, false);
        return inflater.inflate(R.layout.fragment_recyclerview, container, false);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mRecyclerView.addHeaderView(header);
}

**Comment by WaylanPunch** [comment]
@jianghejie @sungerk 已经了解了，谢谢你们！
