### ISSUE TITLE
在使用GridLayoutManager时调用 notifyItemChanged(position)刷新item出错

### ISSUE THREAD

**Issue by S-Co** [jianghejie/XRecyclerView#265]
前置条件   
setLoadingMoreEnabled（false）
setPullRefreshEnabled（false）
调用 notifyItemChanged(position)刷新的位置为position-1

**Comment by itchenqiang** [comment]
因作者重写了getAdpter函数，返回的adapter是咱们传进去的，给recyclerView用的adapter是position+1的，加了头部的下拉刷新的item

**Comment by S-Co** [comment]
@itchenqiang 明白了
