### ISSUE TITLE
GridLayoutManager问题

### ISSUE THREAD

**Issue by q7358582** [jianghejie/XRecyclerView#3]
这个LinearLayoutManager布局好用
但是设置成GridLayoutManager布局后，显示有问题

**Comment by Saxxhw** [comment]
大神！我爱你已经不能表达我对你的敬仰之情啦，嘿嘿

**Comment by Saxxhw** [comment]
急急忙忙down源码看效果。。。发现还没改呢。。。这是计划啊。。。

**Comment by jianghejie** [comment]
已经修改
