### ISSUE TITLE
明显无法使用GridLayoutManager，bug

### ISSUE THREAD

**Issue by e-hai** [jianghejie/XRecyclerView#72]
使用GridLayoutManager的时候，刷新的界面居然成为了item！是否有办法解决呢？
![default](https://cloud.githubusercontent.com/assets/15882634/15172175/b605ca94-1786-11e6-8e4d-93d79d6f946a.png)

**Comment by andyxialm** [comment]
刚试了 也是这样。 UltraPullToRefresh的下拉。 禁用XRecyclerView的下拉。结果第一条的位置被占位了。

**Comment by e-hai** [comment]
这个原因，我是找到了，一定要在setAdapter之前，先setLayoutManager，我估计是XRecyclerView在setAdapter的时候有对layoutMananger进行判断的操作

**Comment by jianghejie** [comment]
这个问题已经解决了，setAdapter和setLayoutManager的顺序不会影响结果
