### ISSUE TITLE
这个开源库写的太棒了。我真是太喜欢了。从各个方面看，都非常优秀。感谢大神！

### ISSUE THREAD

**Issue by ChoicesWang** [jianghejie/XRecyclerView#82]
推荐大家在项目中使用。可以大大提示你的工作效率。

**Comment by lancewong2014** [comment]
确实坑比较多

**Comment by e-hai** [comment]
我个人认为，其实大家有能力的话可以一起修复bug吧。

**Comment by a3349384** [comment]
你可以不用，有必要这么说？素质真低

**Comment by ChoicesWang** [comment]
@a3349384 就只能说好，不能说坏呗。说写的垃圾就是素质低呗？我自己不用，我就是想提醒谨慎使用也是素质低呗？您老人家又站在道德制高点了呗？

**Comment by ChoicesWang** [comment]
@a3349384 既然他选择开源，就有义务把代码写好。既然大家要使用这个开源库，就有义务了解这个库的优缺点。难度你都是拿来就用吗？好不好也不管吗？饭店厨师饭做的难吃，歌手唱歌跑调，按照你的逻辑？你可以不吃啊，你可以不听啊，有必要这么说吗？你平时就是这么将就的活着吗？

**Comment by a3349384** [comment]
既然你愿意这么理解“开源”这个词，我也无话可说。

**Comment by sendtion** [comment]
我来围观一下。说出来缺点也是没问题的，但是上来就说写的垃圾，实在有点不好，你的方式不对。
尊重他人，也是尊重自己。

**Comment by ZeoZhang** [comment]
喷子

**Comment by Gavin-ZYX** [comment]
觉得他写得不好,可以去改他的源码,完善这个框架,岂不更好?

**Comment by lancewong2014** [comment]
慢慢完善吧，现在比开始好多了。

**Comment by lancewong2014** [comment]
我去，一个开源的环境。不是什么都可以容纳的吗？
